name: rankcreditcard
description: Rank Interactive Add Credit Cards
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  flutter_credit_card: ^3.0.7
  fluttertoast: ^8.2.2
  credit_card_scanner: ^1.0.5
  cupertino_icons: ^1.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  build_runner:
  hive_generator:

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/ranklogo.png"
  image_path_ios: "assets/images/ranklogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - data/country_phone_codes.json
    - assets/images/ranklargelogo.jpeg
